version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=knote
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=mykey
      - MINIO_SECRET_KEY=mysecret
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  knote:
    #image: leninospina/knote:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knote
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/knote?authSource=admin
      - MINIO_URL=http://minio:9000
      - MINIO_HOST=http://minio:9000
      - MINIO_ACCESS_KEY=mykey
      - MINIO_SECRET_KEY=mysecret
      - MINIO_BUCKET=knote
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=50MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=50MB
    depends_on:
      - mongo
      - minio
    ports:
      - "8080:8080"


volumes:
  mongo_data:
  minio_data:
